### ISSUE TITLE
Session class hard-codes available API types

### ISSUE THREAD

**Issue by shippy** [sibis-platform/sibispy#37]
...or at least I couldn't figure out how to change it programmatically.

Example:

```yml
# .sibis-general-config.yml
redcap:
  dde_test_token: ...
  endpoint_token: ...
```

```python
import sibispy
from sibispy import sibislogger as slog
import sys
from IPython.display import display

log = slog.init_log()
session = sibispy.Session()
if not session.configure():
    sys.exit(1)

dde_api = session.connect_server('dde_test', True)
# -> {"experiment_site_id": "session.connect_server", "error": "api type dde_test not defined !", "api_types": "['xnat', 'xnat_http', 'import_laptops', 'import_webcnp', 'data_entry', 'redcap_mysql_db', 'browser_penncnp', 'svn_laptop']"}

dde_fem = dde_api.export_fem(format='df')
# -> AttributeError: 'NoneType' object has no attribute 'export_fem'
```

The immediate culprit is [`Session.__init__`](https://github.com/sibis-platform/sibispy/blob/cdd0c481c6020d1f1126da5f8900625336027daf/session.py#L119) / [`Session.connect_server`](https://github.com/sibis-platform/sibispy/blob/cdd0c481c6020d1f1126da5f8900625336027daf/session.py#L145-L173).

To resolve, I think we might need to implement some form of generic server definition, and rewrite Session to construct the server based on config rather than knowing the type based on its name. An imagined config:

```yml
servers:
  import_laptops: &REDCAP_DEFAULT  # to avoid duplication
    type: redcap
    user: torsten
    verify: False
    token: ...
  data_entry:
    <<: *REDCAP_DEFAULT
    token: ....
  xnat:
    type: xnat
# ...
```

Instead of restricting to hard-coded types, `Session.__init__` would look up the keys under `cfg['servers']` and then `Session.connect_server` would then select a connector based on the `type`.
